# Generated by Django 5.2.1 on 2026-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanwallet',
            name='loan_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='total_repaid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
