# Generated by Django 5.2.1 on 2026-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_loanwallet_loan_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanwallet',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='total_repaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
