# Generated by Django 5.2.1 on 2026-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_loanrequest_loanrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanwallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
